---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mint.prefix" . }}-ui-config-map
  namespace: {{ .Release.Namespace }}
data:
  config.js: |
    window.REACT_APP_WELCOME_MESSAGE = {{ .Values.welcome_message | quote }};
    {{- if .Values.default_user }}
    window.REACT_APP_MODEL_CATALOG_DEFAULT_USER= {{ .Values.default_user | quote }};
    {{- end }}
    // Mint Services
    {{- if eq .Values.service.type "NodePort" }}
    window.REACT_APP_CROMO_URL = "http://localhost:{{ include "helm.cromo_node_port" . }}";
    window.REACT_APP_DATA_CATALOG_API = "http://localhost:{{ include "helm.data_catalog_node_port" . }}";
    window.REACT_APP_MODEL_CATALOG_API = "http://localhost:{{ include "helm.model_catalog_api_node_port" . }}/{{ .Values.components.model_catalog_api.api_version }}";
    window.REACT_APP_ENSEMBLE_MANAGER_API = "http://localhost:{{ include "helm.ensemble_manager_node_port" . }}/{{ .Values.components.ensemble_manager.api_version }}";
    window.REACT_APP_GRAPHQL_ENDPOINT = "localhost:{{ include "helm.hasura_node_port" . }}/v1/graphql";
    window.REACT_APP_GRAPHQL_ENABLE_SSL = false;
    {{ else if eq .Values.service.type "ClusterIP" }}
    {{ with .Values.components.cromo }}
    {{ if  .enabled }}
    window.REACT_APP_CROMO_URL = "http{{ if .ingress.tls }}s{{ end }}://{{ with (first .ingress.hosts ) }}{{ .host }}{{ end }}";
    {{ end }}
    {{ end }}
    {{ with .Values.components.data_catalog }}
    {{ if  .enabled }}
    window.REACT_APP_DATA_CATALOG_API = "http{{ if .ingress.tls }}s{{ end }}://{{ with (first .ingress.hosts ) }}{{ .host }}{{ end }}";
    {{ end }}
    {{ end }}
    {{ with .Values.components.model_catalog_api}}
    {{ if  .enabled }}
    window.REACT_APP_MODEL_CATALOG_API = "http{{ if .ingress.tls }}s{{ end }}://{{ with (first .ingress.hosts ) }}{{ .host }}{{ end }}/{{ .api_version }}";
    {{ end }}
    {{ end }}
    {{ with .Values.components.hasura }}
    {{ if  .enabled }}
    window.REACT_APP_GRAPHQL_ENDPOINT = "{{ with (first .ingress.hosts ) }}{{ .host }}{{ end }}/v1/graphql";
    window.REACT_APP_GRAPHQL_ENABLE_SSL = {{ if .ingress.tls  }}true{{else}}false{{ end }};
    {{ end }}
    {{ end }}
    {{ with .Values.components.ensemble_manager }}
    {{ if  .enabled }}
    window.REACT_APP_ENSEMBLE_MANAGER_API = "http{{ if .ingress.tls }}s{{ end }}://{{ with (first .ingress.hosts ) }}{{ .host }}{{ end }}/{{ .api_version }}";
    {{ with .Values.components.ensemble_manager }}
        {{ if  .enabled }}
    	"execution_engine": "localex",
    	"localex": {
        	"codedir":"{{ .environment.data_dir }}/code",
        	"datadir":"{{ .environment.data_dir }}/data",
        	"tempdir":"{{ .environment.data_dir }}/temp",
        	"logdir":"{{ .environment.data_dir }}/logs",
        	"dataurl":"{{ .environment.data_url }}/data",
        	"logurl":"{{ .environment.data_url }}/logs",
        	"parallelism": {{ .number_of_nodes }}
    	},
        {{ end }}
        {{ end }}
    //Execution - Local
    window.REACT_APP_EXECUTION_ENGINE = "localex";
    window.REACT_APP_LOCALEX_CODEDIR = "{{ .environment.data_dir }}/code";
    window.REACT_APP_LOCALEX_DATADIR = "{{ .environment.data_dir }}/data";
    window.REACT_APP_LOCALEX_TEMPDIR = "{{ .environment.data_dir }}/temp";
    window.REACT_APP_LOCALEX_LOGDIR = "{{ .environment.data_dir }}/logs";
    window.REACT_APP_LOCALEX_DATAURL = "{{ .environment.data_url }}/data";
    window.REACT_APP_LOCALEX_LOGURL = "{{ .environment.data_url }}/logs";
    window.REACT_APP_LOCALEX_PARALLEL = "{{ .environment.parallel }}";
    //Execution - Wings
    window.REACT_APP_WINGS_EXPORT_URL = "{{ .environment.wings_export_url }}";
    window.REACT_APP_WINGS_STORAGE = "{{ .environment.wings_storage }}";
    window.REACT_APP_WINGS_DOTPATH = "{{ .environment.wings_dot_path }}";
    window.REACT_APP_WINGS_ONTURL = "{{ .environment.wings_ont_url }}";
    {{ end }}
    {{ end }}

    {{ end }}
    
    // Google API Key
    window.REACT_APP_GOOGLE_MAPS_KEY = {{ .Values.google.maps.key | quote }};

    //Authentications
    window.REACT_APP_AUTH_SERVER = {{ .Values.auth.url | quote }};
    window.REACT_APP_AUTH_REALM = {{ .Values.auth.realm | quote }};
    window.REACT_APP_AUTH_CLIENT_ID = {{ .Values.auth.ui_client_id | quote }};

    //Visualization and Ingestion - Not used any more - Remove ?
    window.REACT_APP_VISUALIZATION_URL = "http://dev.viz.mint.isi.edu";
    window.REACT_APP_INGESTION_API = "http://node1.ingestion.mint.isi.edu/v1.3.0";
